---
# Users and authorisation.
## Visit https://github.com/ffbsee/role-ssh_authorized_keys.git for details config informations

## admins on the gateway that are allowd to execute sudo
admins:
  - l3d
  - mart
  - raoul
  - kpanic
  - alex

## accounts who should be created on gateway
accounts:
  - l3d
  - mart
  - raoul
  - kpanic
  - wolf
  - xperimental
  - alex

## users for remote login with their ssh public key
users:
  l3d:
    - l3d@pinkie.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@business.wingcon.com
    - l3d@derpy.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup-rsa.l3d.yt
  mart:
    - mart@ffbsee.de
    - mart@kirika
    - mart@linux-srfv
    - mart@waldorfschule-ueberlingen.de
  kpanic:
    - kpanic@hirnduenger.de
  raoul:
    - raoul@ccczh
  xperimental:
    - xperimental@id1
    - xperimental@id2
    - xperimental@id3
    - xperimental@id4
  wolf:
    - wolf@rotkaeppchen
  alex:
    - alex@toolbox
    - alex@rsa-toolbox

# fail2ban
fail2ban_maxretry: 10
fail2ban_bantime: "{{ (60 * 10) }}"
fail2ban_banaction: iptables-multiport
fail2ban_jails:
  - name: '{{ fail2ban_ssh_jail_name }}'
    enabled: 'true'

packages_extra:
  - python3-pip

# seme meta informations for the ssh_authorized_keys role
home_sweet_home: false
ssh_public_key_store: 'ssh_authorized_keys'

#telegraf config for all machines
telegraf_agent_package_method: online
telegraf_agent_package: /tmp/telegraf.deb
telegraf_plugins_default:
- plugin: cpu
  config:
    - percpu = true
- plugin: disk
  tags:
    - diskmetrics = true
  tagpass:
    - fstype = [ "ext4", "xfs" ]
  tagdrop:
    - path = [ "/etc", "/etc/telegraf", "/etc/hostname", "/etc/hosts", "/etc/resolv.conf" ]
- plugin: io
- plugin: mem
- plugin: system
- plugin: swap
- plugin: net
- plugin: netstat
- plugin: processes
- plugin: docker
  config:
    - endpoint = "unix:///var/run/docker.sock"
    - timeout = "5s"
telegraf_agent_output:
- type: prometheus_client
  config:
    - listen = ":9273"
    #TODO access control or public?

# prometheus stuff
#TODO access control or public?
prometheus_targets:
  node:
  - targets:
    - gw01.ffbsee.net:9273
    - gw02.ffbsee.net:9273
    - gw03.ffbsee.net:9273
    - gw04.ffbsee.net:9273
    - map.ffbsee.net:9273
    - map.ffbsee.net:9295
    - map.ffbsee.net:8000
    #9273 is telegraf
    #9295 is freifunk exporter


#should go through proxy - I think
grafana_address: 127.0.0.1
grafana_provisioning_synced: true
grafana_dashboard_dir: /opt/grafana/dashboards
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    #localhost could be map here
    url: 'http://localhost:9090'
grafana_dashboards_dir: "{{ grafana_dashboard_dir }}"
grafana_users:
  allow_sign_up: true
  auto_assign_org_role: Viewer
  default_theme: dark

packages_extra:
  - git
  - git-lfs
  - ifupdown
