{
 "title": "Freifunk Bodensee - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(freifunk_router_client_count_total)",
     "legendFormat": "clients"
    },
    { "expr": "count(freifunk_router_meta)", "legendFormat": "routers" }
   ]
  },
  {
   "title": "Firmware Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(freifunk_router_meta{firmware!=\"\",firmware!~\".*server.*\",firmware!~\".*gateway.*\"}) by (firmware)",
     "legendFormat": "{{firmware}}"
    }
   ]
  },
  {
   "title": "Top Routers",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(freifunk_router_client_count_total * on(id) group_left(name) freifunk_router_meta) by (name)"
    }
   ]
  }
 ]
}