{
 "title": "robin per node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": "label_values(node_rx_bytes_total, nodeid)"
   }
  ]
 },
 "panels": [
  {
   "title": "Downstream-Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "node_bw_ff_bps{nodeid=\"$Node\"}",
     "legendFormat": "freifunk"
    },
    {
     "expr": "node_bw_wan_bps{nodeid=\"$Node\"}",
     "legendFormat": "wan"
    }
   ]
  },
  {
   "title": "Gateway-Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "node_gw_ping_ms{nodeid=\"$Node\"}",
     "legendFormat": "ping"
    }
   ]
  },
  {
   "title": "Bytes total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_rx_bytes_total{nodeid=\"$Node\"}",
     "legendFormat": "rx"
    },
    {
     "expr": "node_tx_bytes_total{nodeid=\"$Node\"}",
     "legendFormat": "tx"
    }
   ]
  }
 ]
}