{
 "title": "robin overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bandwidth top 5 and avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(5,node_bw_ff_bps)", "legendFormat": "freifunk_{{nodeid}}" },
    { "expr": "topk(5,node_bw_wan_bps)", "legendFormat": "wan_{{nodeid}}" },
    { "expr": "avg(node_bw_ff_bps)", "legendFormat": "freifunk_avg" },
    { "expr": "avg(node_bw_wan_bps)", "legendFormat": "wan_avg" }
   ]
  },
  {
   "title": "Bytes total sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(node_rx_bytes_total)", "legendFormat": "rx" },
    { "expr": "sum(node_tx_bytes_total)", "legendFormat": "tx" }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(node_gw_ping_ms)", "legendFormat": "ping_avg" },
    { "expr": "min(node_gw_ping_ms)", "legendFormat": "ping_min" },
    { "expr": "max(node_gw_ping_ms)", "legendFormat": "ping_max" }
   ]
  }
 ]
}