---
freifunk_dhcp_server: false 
freifunk_dhcp_relay: true

# meta information about this gateway:
hostname: 'gw01.ffbsee.net'

# fastd configuration:
## list all backbone gateways
fastd_vpn_backbone_configs: 
 - gw04
 - gw03
 - map
 - mate

# define which service should run:
run_mesh: 'true'
run_gateway: 'true'
run_webserver: 'false'
run_icvpn: 'true'
run_map: 'false'
run_stats: 'false'
da_laueft_ein_dhcp_relay: 'true'
nodelist: false

# ipv6 radvd
ipv6_uplink_announcen: true
radv_AdvDefaultPreference: 'medium' # low - medium - high
ipv6_radv_suffix: ':1'
ipv6_radv_address: '{{ ipv6_prefix }}{{ ipv6_radv_suffix }}'
ipv6_radv_prefix: '{{ ipv6_prefix }}:/64'

# batman - used addresses
bat0_mac_address: '82:77:f7:59:2f:f4'
ipv4_mesh_address: '10.15.224.1' 
ipv6_suffix: ':1'
wan_base_interface: 'enp2s0'
wan_vlan_id: ''
wan_interface: '{{ wan_base_interface }}{% if wan_vlan_id != "" %}.{{ wan_vlan_id }}{% endif %}'
wan_ipv4_ip: '144.76.175.21'
wan_ipv6_network: '2a01:4f8:200:5308::/64'

# IPv6 address for nodes autoupdater
mesh_ipv6_extra_addr: ''

# add addresses from variables
ipv6_address: '{{ ipv6_prefix }}{{ ipv6_suffix }}'
mesh_ipv6_address: '{{ ipv6_address }}'

# optional define fastd secret key:
## else a key will generatet automatically
## if it is not already avaliable on server
fastd_secret_key: ''
fastd_peer_limit: '' # should we limit the fastd peer limits

# some rules for the iptables/firewall
# should we only use the wan interface on some rules? (recomendet)
block_rfc1918_interface: "{{ wan_base_interface }}"

debian: '10'
number_of_cores: '8'
