---
hostname: 'gw03.ffbsee.net'
gwnumber: '03'

ipv4_mesh_address: '10.15.224.3'
bat0_mac_address: '26:47:2f:02:f1:45'

ipv6_suffix: ':3'
ipv6_radv_suffix: ':3'
ipv6_address: '{{ ipv6_prefix }}{{ ipv6_suffix }}'
mesh_ipv6_extra_addr: 'fdef:1701:b5ee:23::42'
mesh_ipv6_address: '{{ ipv6_address }}'
ipv6_radv_address: '{{ ipv6_prefix }}{{ ipv6_radv_suffix }}'
ipv6_radv_prefix: '{{ ipv6_prefix }}:/64'

wan_ipv6_network: '2001:4ba0:92c1:c::/64'
wan_ipv6_ip: '2001:4ba0:ffa4:115::2'
wan_base_interface: 'eth0'
wan_vlan_id: ''
wan_interface: '{{ wan_base_interface }}{% if wan_vlan_id != "" %}.{{ wan_vlan_id }}{% endif %}'
wan_ipv4_ip: '89.163.145.35'

fastd_secret_key: ''
vpn_on_port_443: 'false'

run_mesh: 'true'
run_gateway: 'true'
run_webserver: 'true'
run_icvpn: 'false'
run_map: 'true'
run_stats: 'false'
da_laueft_ein_dhcp_relay: 'true'
freifunk_dhcp_relay: 'true'

fastd_peer_limit: ''
fastd_vpn_backbone_configs:
  - gw01
  - gw04
  - map
  - mate

vxlantogw01: '1'
vxlantogw03: '0'
vxlantogw04: '1'
vxlantometa: '1'

ipv6_uplink_announcen: 'true'
radv_AdvDefaultPreference: 'medium'

debian: '11'
number_of_cores: '8'
freifunk_karte_api: 'true'

nodelist: 'true'

block_rfc1918_interface: 'eth0'
