---
hostname: 'map.ffbsee.net'
gwnumber: '06'
  
ipv4_mesh_address: '10.15.224.6'
bat0_mac_address: '86:00:00:2c:de:52'
wireguardipaddress: 'fd42:dead:beef:4::6'
vxlanmac: '66:61:17:75:32:af'
vxlanendpoints: '\"fd42:dead:beef:4::1\" \"fd42:dead:beef:4::3\" \"fd42:dead:beef:4::4\" \"fd42:dead:beef:4::5\"'
vxlanbackbonename: 'vxbackbone'

ipv6_suffix: ':6'
ipv6_radv_suffix: ':1'
ipv6_address: '{{ ipv6_prefix }}{{ ipv6_suffix }}'
mesh_ipv6_extra_addr: ''
mesh_ipv6_address: '{{ ipv6_address }}'
ipv6_radv_address: '{{ ipv6_prefix }}{{ ipv6_radv_suffix }}'
ipv6_radv_prefix: '{{ ipv6_prefix }}:/64'

wan_ipv6_network: '2a01:4f8:c2c:9583::/64'
wan_ipv6_ip: '2a01:4f8:c2c:9583::1'
wan_base_interface: 'eth0'
wan_vlan_id: ''
wan_interface: '{{ wan_base_interface }}{% if wan_vlan_id != "" %}.{{ wan_vlan_id }}{% endif %}'
wan_ipv4_ip: '159.69.201.167'

fastd_secret_key: ''
vpn_on_port_443: 'false'

run_mesh: 'true'
run_gateway: 'false'
run_webserver: 'true'
run_icvpn: 'false'
run_map: 'true'
run_stats: 'false'
da_laueft_ein_dhcp_relay: 'false'
freifunk_dhcp_server: 'false'

fastd_vpn_backbone_configs:
  - gw01
  - gw04
fastd_peer_limit: ''

vxlantogw01: '1'
vxlantogw03: '1'
vxlantogw04: '1'
vxlantometa: '0'  

ipv6_uplink_announcen: 'false'
radv_AdvDefaultPreference: 'low'

debian: '11'
freifunk_karte_api: 'true'

nodelist: 'true'

block_rfc1918_interface: "{{ wan_base_interface }}"

# we do not host any presentations here
presentation_webserver: false

packages_extra:
  - git
  - git-lfs
  - ifupdown
  - python3-pip

number_of_cores: 1
